
# Plantilla de configuración de MySQL para CrediYa.
# Servidor local, puerto 3306, base de datos crediya_db
db.url=jdbc:mysql://localhost:3306/crediya_db?allowPublicKeyRetrieval=true
db.user=root
db.password=Julian1125?
